### ISSUE TITLE
Fix ALL console.errros

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/aletheia#146]
Before the UI render can go in production on axa.ch. all the `console.errors` have to be removed/fixed. This is important as on AEM a lot of JavaScript runs and clean and proper error handling and displaying is a must

**Comment by mjenny** [comment]
#24 #23 #22 #21 #20 #19 #18 #17 #16 #15 #14 #13 #12

**Comment by AndyOGo** [comment]
#167
