### ISSUE TITLE
Do we need overflow: auto?

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/aletheia#151]
Do you need `overflow: auto` or was it just implemented as "circuit breaker" (defensive programming)? I think we can remove it. If not, we need to find a solution as AEM should not have to override SPAs css. Happy for FB. 

![mai-23-2018 14-44-47](https://user-images.githubusercontent.com/275235/40425319-5844319c-5e98-11e8-9afa-b36eaa0c7fd0.gif)

**Comment by AndyOGo** [comment]
I don't see it's need 🤔

**Comment by lina-salih** [comment]
I don't think we need  ``overflow:` auto `

**Comment by lina-salih** [comment]
Leave a comment

**Comment by lina-salih** [comment]
I think we don't need `overflow: auto`

**Comment by LucaMele** [comment]
ok so we should remove it. thank you for your help :)
