### ISSUE TITLE
Reboot css from patterns lib inside ui renderer makes funny effects

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/aletheia#178]
Dropdown icon only moves when js of ui render loads

![bildschirmfoto 2018-06-07 um 09 51 16](https://user-images.githubusercontent.com/275235/41085913-a29a1472-6a38-11e8-9c3f-5bfa21cf92e8.png)

**Comment by AndyOGo** [comment]
related https://github.com/axa-ch/patterns-library/issues/457

**Comment by LucaMele** [comment]
sorry always so aem issue
