### ISSUE TITLE
Segment + Bullet Radio infinite loop

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/aletheia#50]
Having a **Segmented Radio** and a **Bullet Radio** combined together at one screen results in an infinite loop caused by infinite API calls.

![2018-04-23_134434](https://user-images.githubusercontent.com/914443/39125068-13f1d578-46fe-11e8-84e4-14642599747c.png)

**Comment by mjenny** [comment]
Network Tab Screenshot (Request / Response)
![image](https://user-images.githubusercontent.com/4191545/39243459-c939d878-488d-11e8-8649-3f56a4aad949.png)
