### ISSUE TITLE
All Components are wrapped by Field

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/aletheia#66]
Currently All components are wrapped by `<Field />` within the `<ComponentRenderer>`.
Thus all validations have to be separated from the individual components.
https://github.com/axa-ch/aletheia/blob/develop/src/renderers/ComponentRenderer.js#L18-L51

I think it could be much more beneficial to keep related code together and hence utilize the `<Field />` inside each component individually.
This way we can easily define custom validations at component level and know where they match.

**Comment by AndyOGo** [comment]
May I'm wrong, if the used validation is defined within the JSON schema by the BPM process 🤔

**Comment by mjenny** [comment]
Might actually be correct for our usage.
