### ISSUE TITLE
HTTP Error 500 when quickly changing options

### ISSUE THREAD

**Issue by mjenny** [axa-ch/aletheia#71]
There is an issue with the quick change e.g. between radio buttons.
This is caused by not waiting on the response from BPME already sending the next request, arguably with the same screen instance id as before.

The screen recording below illustrates the issue:
![ui-renderer-quick-option-change-500-error](https://user-images.githubusercontent.com/4191545/39252510-1ccfc958-48a6-11e8-9c5a-9306871a7fdc.gif)

**Comment by AndyOGo** [comment]
Existing designs for **Inactive/Disabled** states can be found here:
https://design.axa.com/web-guidelines/forms-update
