### ISSUE TITLE
Release script broken at windows

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/aletheia#79]
The release script doesn't work at windows for:
- logging - logs within `child_process.exec` callback don't show up in console (the main process's `stdin` and `stdout`)
- Node modules aren't found within NPM scrips #78

**Comment by mjenny** [comment]
Issue will be addressed in https://github.com/axa-ch/patterns-library/issues/210
But has to be fixed afterwards.

**Comment by mjenny** [comment]
Duplicates #78
